Repository TUK2024CD-Studymate/backend, pull requests merged in 2024-03, with the labels that each got.

#84 [Feat] 스터디기록 총 공부시간 저장 및 직렬화 후 보내도록 구현
  back-end/src/main/java/com/studymate/backend/studycalender/StudyCalenderMapper.java
  back-end/src/main/java/com/studymate/backend/studycalender/domain/StudyCalender.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/StudyCalenderService.java
Labels: 기능구현

#86 [Feat] 자신이 쓴 게시물 조회 api 설계
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostRepository.java
  back-end/src/main/java/com/studymate/backend/post/service/PostService.java
Labels: 기능구현

#88 [Feat] 회원가입시 전화번호 추가 기능
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberRequest.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
Labels: 기능구현

#90 [refactor] Swagger 관련 예시 데이터 수정
  back-end/src/main/java/com/studymate/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/studymate/backend/comment/dto/request/CommentRequest.java
  back-end/src/main/java/com/studymate/backend/file/controller/ProfileImgController.java
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberRequest.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/post/controller/PostController.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostRequestDto.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostUpdateRequestDto.java
  back-end/src/main/java/com/studymate/backend/question/controller/QuestionController.java
  back-end/src/main/java/com/studymate/backend/studycalender/controller/StudyCalenderController.java
Labels: 리팩토링

#92 [refactor] Swagger 관련 예시 데이터 추가 수정
  back-end/src/main/java/com/studymate/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderUpdateRequest.java
Labels: 리팩토링

#95 [Refactor] 스터디 기록 생성시 반환값 JSON 형태의 key:value 값으로 넘겨주도록 수정
  back-end/src/main/java/com/studymate/backend/studycalender/controller/StudyCalenderController.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/StudyCalenderService.java
Labels: 리팩토링

#97 [feat] FCM 설정 및 구현
  back-end/.gitignore
  back-end/build.gradle
  back-end/docker-compose.yml
  back-end/src/main/java/com/studymate/backend/commons/firebase/FCMService.java
  back-end/src/main/java/com/studymate/backend/commons/firebase/FCMTokenManager.java
  back-end/src/main/java/com/studymate/backend/commons/firebase/PushNotificationService.java
  back-end/src/main/java/com/studymate/backend/config/fcm/FCMInitializer.java
  back-end/src/main/java/com/studymate/backend/config/redis/RedisConfig.java
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/domain/Matching.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/java/com/studymate/backend/member/MemberRepository.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberLoginRequest.java
  back-end/src/main/java/com/studymate/backend/member/service/MemberService.java
  back-end/src/main/resources/application.yml
  back-end/src/main/resources/firebase/studymate-92070-firebase-adminsdk-t4116-5c71b9db48.json
  back-end/src/test/java/com/studymate/backend/FCMPushNotification.java
Labels: 기능구현

#101 [Feat] Zoom Api 재설계
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/zoom/controller/ZoomController.java
  back-end/src/main/resources/templates/zoomLogin.html
Labels: 기능구현

#104 [feat] 해당 게시물 댓글 수 반환 기능 추가
  back-end/src/main/java/com/studymate/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/studymate/backend/comment/repository/CommentRepository.java
  back-end/src/main/java/com/studymate/backend/comment/service/CommentService.java
Labels: 기능구현

#106 [Feat] 좋아요 기능 구현
  back-end/build.gradle
  back-end/src/main/generated/com/studymate/backend/comment/domain/QComment.java
  back-end/src/main/generated/com/studymate/backend/file/domain/QProfileImg.java
  back-end/src/main/generated/com/studymate/backend/global/QBaseTimeEntity.java
  back-end/src/main/generated/com/studymate/backend/heart/domain/QHeart.java
  back-end/src/main/generated/com/studymate/backend/matching/domain/QMatching.java
  back-end/src/main/generated/com/studymate/backend/member/domain/QAuthority.java
  back-end/src/main/generated/com/studymate/backend/member/domain/QMember.java
  back-end/src/main/generated/com/studymate/backend/post/domain/QPost.java
  back-end/src/main/generated/com/studymate/backend/question/domain/QQuestion.java
  back-end/src/main/generated/com/studymate/backend/studycalender/domain/QStudyCalender.java
  back-end/src/main/generated/com/studymate/backend/zoom/domain/QZoomMeeting.java
  back-end/src/main/java/com/studymate/backend/config/querlydsl/QuerydslConfig.java
  back-end/src/main/java/com/studymate/backend/heart/HeartRepository.java
  back-end/src/main/java/com/studymate/backend/heart/controller/HeartController.java
  back-end/src/main/java/com/studymate/backend/heart/domain/Heart.java
  back-end/src/main/java/com/studymate/backend/heart/service/HeartService.java
  back-end/src/main/java/com/studymate/backend/post/PostMapper.java
  back-end/src/main/java/com/studymate/backend/post/domain/Post.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostResponseDto.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostCustomRepository.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostRepository.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostRepositoryImpl.java
  back-end/src/main/java/com/studymate/backend/zoom/controller/ZoomController.java
Labels: 기능구현

#108 [Feat] 사용자가 좋아요를 누른 게시물 조회 기능 추가
  back-end/src/main/java/com/studymate/backend/heart/HeartRepository.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/post/domain/Post.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostRepository.java
  back-end/src/main/java/com/studymate/backend/post/service/PostService.java
Labels: 기능구현

#110 [Feat] 매칭 신청시 LMS로 알림 구현
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/java/com/studymate/backend/message/service/MessageService.java
  back-end/src/main/java/com/studymate/backend/zoom/controller/ZoomController.java
  back-end/src/main/resources/application.yml
Labels: 기능구현

#102 [feat] 채팅 구현
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatController.java
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatRoomController.java
  back-end/src/main/java/com/studymate/backend/chat/domain/ChatMessage.java
  back-end/src/main/java/com/studymate/backend/chat/domain/ChatRoom.java
  back-end/src/main/java/com/studymate/backend/chat/repository/ChatRoomRepository.java
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/config/security/jwt/TokenProvider.java
  back-end/src/main/java/com/studymate/backend/global/config/WebSocketConfig.java
  back-end/src/main/java/com/studymate/backend/global/stomp/StompExceptionHandler.java
  back-end/src/main/java/com/studymate/backend/global/stomp/StompHandler.java
  back-end/src/main/java/com/studymate/backend/member/domain/UserDetail.java
  back-end/src/main/resources/application.yml
  back-end/src/main/resources/template/chat/room.ftl
  back-end/src/main/resources/template/chat/roomdetail.ftl
Labels: 기능구현

#114 [Feat] 채팅 api에 스웨거 추가
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatRoomController.java
Labels: 기능구현, 기타/세팅

#116 [Feat] 채팅 /pub에 roomId 추가
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatController.java
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatRoomController.java
Labels: 기능구현

#118 [refactor] 시작일시 및 종료일시 검증시 기준 시간을 대한민국 서울시로 변경
  back-end/src/main/java/com/studymate/backend/matching/MatchingRepository.java
  back-end/src/main/java/com/studymate/backend/studycalender/StudyCalenderValidator/StudyCalenderValidator.java
Labels: 리팩토링

#120 [refactor] 멘토 매칭신청 및 인증번호 대표번호 변경
  back-end/src/main/resources/application.yml
Labels: 리팩토링

#123 [chore] 도커파일 및 컴포즈 수정
  back-end/Dockerfile
  back-end/docker-compose.yml
Labels: 기타/세팅

#125 [Feat] PostResponse값에 댓글 수 같이 반환하도록 추가
  back-end/src/main/java/com/studymate/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/studymate/backend/post/PostMapper.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostResponseDto.java
Labels: 기능구현

#130 [refactor] 줌 리다이렉션 URL 변경
  back-end/src/main/java/com/studymate/backend/zoom/controller/ZoomController.java
Labels: 리팩토링
