Repository TUK2024CD-Studymate/backend, pull requests merged in 2024-04, with the labels that each got.

#134 [fix] ManyToOne 어노테이션 fetch를 LAZY로 수정
  back-end/src/main/java/com/studymate/backend/comment/domain/Comment.java
  back-end/src/main/java/com/studymate/backend/post/domain/Post.java
Labels: 오류수정

#135 [Feat] KMP 알고리즘을 활용해 멘토를 매칭해주는 API 구현
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/resources/data.sql
Labels: 기능구현

#136 [Feat] KMP 알고리즘 구현
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberRequest.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/question/domain/Question.java
  back-end/src/main/java/com/studymate/backend/question/dto/QuestionCreateRequest.java
  back-end/src/main/java/com/studymate/backend/question/dto/QuestionResponse.java
Labels: 기능구현

#137 [Feat] 로그아웃 API 구현
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/config/security/jwt/JwtFilter.java
  back-end/src/main/java/com/studymate/backend/config/security/jwt/JwtSecurityConfig.java
  back-end/src/main/java/com/studymate/backend/config/security/jwt/TokenProvider.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberLoginRequest.java
  back-end/src/main/java/com/studymate/backend/member/dto/TokenRequestDto.java
  back-end/src/main/java/com/studymate/backend/member/dto/TokenResponseDto.java
  back-end/src/main/java/com/studymate/backend/member/service/MemberService.java
Labels: 기능구현

#139 [Refactor] 좋아요 ResponseData 변경
  back-end/src/main/java/com/studymate/backend/heart/HeartMapper.java
  back-end/src/main/java/com/studymate/backend/heart/controller/HeartController.java
  back-end/src/main/java/com/studymate/backend/heart/domain/Heart.java
  back-end/src/main/java/com/studymate/backend/heart/dto/HeartResponse.java
  back-end/src/main/java/com/studymate/backend/heart/service/HeartService.java
Labels: 기능구현

#143 [chore] 도커파일 및 컴포즈 파일 개발용/배포용 분리
  back-end/Dockerfile.dev
  back-end/docker-compose.dev.yml
Labels: 기타/세팅

#146 [Refactor] 회원정보 조회시 반환값 변경
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
Labels: 리팩토링

#148 [Feat] GPT 연동
  back-end/docker-compose.dev.yml
  back-end/docker-compose.yml
  back-end/src/main/java/com/studymate/backend/config/openAi/OpenAiConfig.java
  back-end/src/main/resources/application.yml
Labels: 기능구현

#149 [Feat] 질문에 대한 맞춤법 및 질문을 자연스럽게 정제해주는 api 개발
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/global/gpt/dto/GPTRequest.java
  back-end/src/main/java/com/studymate/backend/global/gpt/dto/GPTResponse.java
  back-end/src/main/java/com/studymate/backend/global/gpt/dto/Message.java
  back-end/src/main/java/com/studymate/backend/global/gpt/dto/PromptMessageRequest.java
  back-end/src/main/java/com/studymate/backend/global/gpt/dto/PromptMessageResponse.java
  back-end/src/main/java/com/studymate/backend/question/controller/QuestionController.java
  back-end/src/main/java/com/studymate/backend/question/dto/QuestionAiRequest.java
  back-end/src/main/java/com/studymate/backend/question/dto/QuestionAiResponse.java
  back-end/src/main/java/com/studymate/backend/question/service/QuestionService.java
Labels: 기능구현

#151 [Refactor] 스터디기록 생성 및 수정시 초(ss)를 받은 후 전체시간 반환시 초 까지 반환하도록 변경
  back-end/src/main/java/com/studymate/backend/studycalender/controller/StudyCalenderController.java
  back-end/src/main/java/com/studymate/backend/studycalender/domain/StudyCalender.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderCreateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/StudyCalenderService.java
Labels: 리팩토링

#154 [Feat] 회원 로그인 판별값 추가 구현
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
  back-end/src/main/java/com/studymate/backend/member/service/MemberService.java
  back-end/src/main/resources/data.sql
Labels: 기능구현

#156 [Feat] AWS RDS 연동
  back-end/docker-compose.dev.yml
  back-end/docker-compose.yml
  back-end/src/main/resources/application.yml
  back-end/src/main/resources/data.sql
Labels: 기능구현, 기타/세팅
