Repository TUK2024CD-Studymate/backend, pull requests merged in 2024-05, with the labels that each got.

#160 [fix] SSE 유저 토큰으로 구별되도록 수정 + 매칭 시에도 알림 가도록 추가
  back-end/src/main/java/com/studymate/backend/comment/service/CommentService.java
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/config/security/jwt/TokenProvider.java
  back-end/src/main/java/com/studymate/backend/heart/service/HeartService.java
  back-end/src/main/java/com/studymate/backend/matching/dto/MatchingSseResponse.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/java/com/studymate/backend/notification/controller/NotificationController.java
  back-end/src/main/java/com/studymate/backend/notification/service/NotificationService.java
Labels: 기능구현, 오류수정

#159 [Feat] GPT 기반 멘토 추천 기능 구현
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/dto/JsonMentorResponse.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
Labels: 기능구현

#162 [Refactor] 스터디기록 필드 형식 수정
  back-end/src/main/java/com/studymate/backend/studycalender/StudyCalenderMapper.java
  back-end/src/main/java/com/studymate/backend/studycalender/domain/StudyCalender.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderCreateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/StudyCalenderService.java
Labels: 리팩토링

#165 [fix] 브랜치 꼬임 복구
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/chat/domain/ChatRoom.java
  back-end/src/main/java/com/studymate/backend/chat/dto/ChatRoomRes.java
  back-end/src/main/java/com/studymate/backend/chat/repository/ChatRoomRepository.java
  back-end/src/main/java/com/studymate/backend/chat/repository/UserChatRoomRepository.java
  back-end/src/main/java/com/studymate/backend/comment/service/CommentService.java
  back-end/src/main/java/com/studymate/backend/global/stomp/StompHandler.java
  back-end/src/main/resources/data.sql
Labels: 오류수정

#168 [fix] GPT 반환 메세지 형식 검증을 위한 while문 로직 수정 및 로깅처리
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
Labels: 오류수정

#172 [fix] 토큰 유효해야만 stomp 연결되게끔 수정
  back-end/src/main/java/com/studymate/backend/global/stomp/StompHandler.java
Labels: 오류수정

#174 [Feat] 멘토 매칭 신청시 LMS 알림에서 카카오톡 알림톡으로 변경
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/resources/application.yml
Labels: 기능구현

#176 [fix] isLogin 로직 복구
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/controller/MemberController.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
Labels: 오류수정

#178 [Feat] 스터디 과목 CRUD 및 기존 스터디기록 코드 리팩토링
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/studycalender/controller/StudyCalenderController.java
  back-end/src/main/java/com/studymate/backend/studycalender/domain/CalenderSubject.java
  back-end/src/main/java/com/studymate/backend/studycalender/domain/StudyCalender.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderCreateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/SubjectCreateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/SubjectListResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/SubjectResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/SubjectUpdateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/mapper/CalenderSubjectMapper.java
  back-end/src/main/java/com/studymate/backend/studycalender/mapper/StudyCalenderMapper.java
  back-end/src/main/java/com/studymate/backend/studycalender/repository/CalenderSubjectRepository.java
  back-end/src/main/java/com/studymate/backend/studycalender/repository/StudyCalenderRepository.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/CalenderSubjectService.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/StudyCalenderService.java
Labels: 기능구현, 리팩토링

#182 [feat] 채팅 읽음처리 기능 구현
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatController.java
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatMessageController.java
  back-end/src/main/java/com/studymate/backend/chat/domain/ChatMessage.java
  back-end/src/main/java/com/studymate/backend/chat/dto/ChatMessageRes.java
  back-end/src/main/java/com/studymate/backend/chat/dto/ChatRoomRes.java
  back-end/src/main/java/com/studymate/backend/chat/mapper/ChatMapper.java
  back-end/src/main/java/com/studymate/backend/chat/service/ChatService.java
  back-end/src/main/java/com/studymate/backend/chat/service/MessageService.java
Labels: 기능구현, 오류수정

#183 [refactor] 기존 회원 카테고리 세분화
  back-end/src/main/java/com/studymate/backend/member/domain/Interests.java
Labels: 리팩토링

#188 [Feat] 프로필 사진 API 구현
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/config/s3/S3Config.java
  back-end/src/main/java/com/studymate/backend/file/FileMapper.java
  back-end/src/main/java/com/studymate/backend/file/ProfileImgRepository.java
  back-end/src/main/java/com/studymate/backend/file/controller/ProfileImgController.java
  back-end/src/main/java/com/studymate/backend/file/domain/ProfileImg.java
  back-end/src/main/java/com/studymate/backend/file/dto/S3Url.java
  back-end/src/main/java/com/studymate/backend/file/service/ProfileImgService.java
  back-end/src/main/java/com/studymate/backend/file/service/S3UploadService.java
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
  back-end/src/main/resources/application.yml
Labels: 기능구현

#190 [Feat] AI 매칭시 멘토 일치 퍼센트률 반환되도록 구현
  back-end/src/main/java/com/studymate/backend/matching/MatchingMemberMapper.java
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/dto/MatchingMemberResponse.java
  back-end/src/main/java/com/studymate/backend/matching/dto/MatchingResponse.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
Labels: 기능구현

#192 [Refactor] 리뷰 조회시 프로필사진URL 반환하도록 리팩토링
  back-end/src/main/java/com/studymate/backend/review/ReviewMapper.java
  back-end/src/main/java/com/studymate/backend/review/dto/ReviewResponse.java
Labels: 기능구현

#194 [Refactor] 게시물 및 댓글 반환시 프로필사진 URL까지 반환하도록 변경
  back-end/src/main/java/com/studymate/backend/comment/dto/response/CommentListResponse.java
  back-end/src/main/java/com/studymate/backend/comment/dto/response/CommentResponse.java
  back-end/src/main/java/com/studymate/backend/comment/service/CommentService.java
  back-end/src/main/java/com/studymate/backend/post/PostMapper.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostResponseDto.java
Labels: 리팩토링
