Repository TUK2024CD-Studymate/backend, pull requests merged in 2024-06, with the labels that each got.

#196 [Refactor] 리뷰 개수 반환 로직 수정
  back-end/src/main/java/com/studymate/backend/matching/MatchingMemberMapper.java
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/member/service/MemberService.java
  back-end/src/main/java/com/studymate/backend/review/ReviewMapper.java
  back-end/src/main/java/com/studymate/backend/review/dto/ReviewResponseList.java
Labels: 리팩토링

#199 [Fix] 채팅방 rabbitmq 추가 및 생성 로직 수정
  back-end/build.gradle
  back-end/docker-compose.dev.yml
  back-end/docker-compose.yml
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatController.java
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatMessageController.java
  back-end/src/main/java/com/studymate/backend/chat/domain/ChatRoom.java
  back-end/src/main/java/com/studymate/backend/chat/repository/ChatRoomRepository.java
  back-end/src/main/java/com/studymate/backend/chat/service/ChatService.java
  back-end/src/main/java/com/studymate/backend/chat/service/MessageService.java
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/global/config/RabbitConfig.java
  back-end/src/main/java/com/studymate/backend/global/config/WebSocketConfig.java
  back-end/src/main/java/com/studymate/backend/global/constant/RabbitMQ.java
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/resources/application.yml
Labels: 기능구현, 오류수정

#202 [fix] 채팅 관련 오류 수정
  back-end/src/main/java/com/studymate/backend/chat/controller/ChatController.java
  back-end/src/main/java/com/studymate/backend/chat/dto/ChatMessageRes.java
  back-end/src/main/java/com/studymate/backend/chat/dto/ChatRoomRes.java
  back-end/src/main/java/com/studymate/backend/chat/mapper/ChatMapper.java
  back-end/src/main/java/com/studymate/backend/chat/service/ChatService.java
  back-end/src/main/java/com/studymate/backend/global/constant/DefaultProfileImg.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
Labels: 기능구현, 오류수정

#203 [Refactor] 기본프로필사진 URL 재설정
  back-end/src/main/java/com/studymate/backend/comment/dto/response/CommentResponse.java
  back-end/src/main/java/com/studymate/backend/matching/MatchingMemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/post/PostMapper.java
  back-end/src/main/java/com/studymate/backend/review/ReviewMapper.java
Labels: 리팩토링

#205 [fix] 자신에게 채팅요청 못하도록 예외처리
  back-end/src/main/java/com/studymate/backend/chat/service/ChatService.java
  back-end/src/main/java/com/studymate/backend/post/domain/Post.java
Labels: 오류수정
