Repository TUK2024CD-Studymate/backend, pull requests merged in 2024-02, with the labels that each got.

#18 [chore] 도커 세팅 완료
  back-end/.gitignore
  back-end/Dockerfile
  back-end/build.gradle
  back-end/docker-compose.yml
  back-end/src/main/resources/application.yml
Labels: 기타/세팅

#20 [chore] 백엔드 도커 재세팅 완료
  back-end/docker-compose.yml
  back-end/src/main/resources/application.yml
Labels: 기타/세팅

#21 [chore] data.sql 수정
  back-end/src/main/resources/data.sql
Labels: 기타/세팅

#22 [chore] 백엔드 도커 세팅 진짜 완료
  back-end/build.gradle
  back-end/docker-compose.yml
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/resources/data.sql
Labels: 기타/세팅, 오류수정

#27 feat: StudyCalenderController 내부 전체조회 api 설계
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/studycalender/controller/StudyCalenderController.java
Labels: 기능구현

#29 [feat]: StudyCalender저장소 내부 전체조회를 위한 쿼리 메소드 설계
  back-end/src/main/java/com/studymate/backend/studycalender/StudyCalenderRepository.java
Labels: 기능구현

#30 [feat] CalenderListResponseDTO 설계
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderListResponse.java
Labels: 기능구현

#32 [feat] StudyCalenderMapper내부 toListResponse 메서드 추가 설계
  back-end/src/main/java/com/studymate/backend/studycalender/StudyCalenderMapper.java
Labels: 기능구현

#37 [feat] PostRepository에 키워드 검색기능 추가
  back-end/.env
  back-end/.gitignore
  back-end/Dockerfile
  back-end/docker-compose.yml
  back-end/src/main/java/com/studymate/backend/member/service/MemberService.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostRepository.java
  back-end/src/main/resources/data.sql
Labels: 기능구현

#39 [feat] PostController에 키워드 검색 기능 추가
  back-end/src/main/java/com/studymate/backend/post/controller/PostController.java
Labels: 기능구현

#38 feat: PostService에 게시글 검색 기능 추가
  back-end/src/main/java/com/studymate/backend/post/service/PostService.java
Labels: 기능구현

#46 [feat] PostRequestDto에서 userid 삭제
  back-end/src/main/java/com/studymate/backend/post/dto/PostRequestDto.java
Labels: 오류수정

#48 [refactor] StudyCalenderService, ResponseDto, Mapper클래스에 id값 추가
  back-end/src/main/java/com/studymate/backend/studycalender/StudyCalenderMapper.java
  back-end/src/main/java/com/studymate/backend/studycalender/controller/StudyCalenderController.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/service/StudyCalenderService.java
Labels: 리팩토링

#49 [Feat] 줌 API 구현
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/config/security/SecurityConfig.java
  back-end/src/main/java/com/studymate/backend/zoom/ZoomTokenRepository.java
  back-end/src/main/java/com/studymate/backend/zoom/controller/ZoomController.java
  back-end/src/main/java/com/studymate/backend/zoom/domain/ZoomMeeting.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomGlobalDialInNumbersDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomInterpreterDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomMeetingObjectDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomMeetingOccurenceDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomMeetingRecurrenceDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomMeetingSettingsDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/dto/ZoomMeetingTrackingFieldsDTO.java
  back-end/src/main/java/com/studymate/backend/zoom/service/ZoomService.java
  back-end/src/main/java/com/studymate/backend/zoom/util/DecEncUtil.java
Labels: 기능구현

#57 [fix] ZoomController 회의생성 앤드포인트 재설정
  back-end/src/main/java/com/studymate/backend/zoom/controller/ZoomController.java
Labels: 오류수정

#52 [feat] 게시판 댓글 기능 - CommentRepository 구현 완료
  back-end/src/main/java/com/studymate/backend/comment/repository/CommentRepository.java
Labels: 기능구현

#54 [feat] 게시판 댓글 기능 - CommentController 구현 완료
  back-end/src/main/java/com/studymate/backend/comment/controller/CommentController.java
Labels: 기능구현

#51 [feat] 게시판 댓글 기능 - Comment Response/Request DTO 구현 완료
  back-end/src/main/java/com/studymate/backend/comment/dto/CommentRequestDto.java
  back-end/src/main/java/com/studymate/backend/comment/dto/CommentResponseDto.java
Labels: 기능구현

#53 [feat] 게시판 댓글 기능 - CommentService 구현 완료
  back-end/src/main/java/com/studymate/backend/comment/CommentMapper.java
  back-end/src/main/java/com/studymate/backend/comment/service/CommentService.java
  back-end/src/main/java/com/studymate/backend/comment/service/CommentServiceValidator.java
  back-end/src/main/java/com/studymate/backend/post/service/PostService.java
Labels: 기능구현

#60 [Fix] StudyCalenderDTO에 날짜 역직렬화, 직렬화 추가 적용
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderCreateRequest.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderResponse.java
  back-end/src/main/java/com/studymate/backend/studycalender/dto/CalenderUpdateRequest.java
Labels: 오류수정

#62 [fix] 게시글 생성, 수정 시간 형식 수정 완료
  back-end/build.gradle
  back-end/src/main/java/com/studymate/backend/global/BaseTimeEntity.java
  back-end/src/main/java/com/studymate/backend/post/PostMapper.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostResponseDto.java
Labels: 오류수정

#64 Refactor/#63
  back-end/src/main/java/com/studymate/backend/comment/CommentMapper.java
  back-end/src/main/java/com/studymate/backend/comment/controller/CommentController.java
  back-end/src/main/java/com/studymate/backend/comment/dto/CommentRequestDto.java
  back-end/src/main/java/com/studymate/backend/comment/dto/CommentResponseDto.java
  back-end/src/main/java/com/studymate/backend/comment/dto/request/CommentRequest.java
  back-end/src/main/java/com/studymate/backend/comment/dto/response/CommentListResponse.java
  back-end/src/main/java/com/studymate/backend/comment/dto/response/CommentResponse.java
  back-end/src/main/java/com/studymate/backend/comment/service/CommentService.java
  back-end/src/main/java/com/studymate/backend/post/repository/PostRepository.java
  back-end/src/main/java/com/studymate/backend/post/service/PostService.java
Labels: 리팩토링

#71 [Feat] 회원가입시 필요한 필드 수정 및 로직 변경
  back-end/src/main/java/com/studymate/backend/file/ProfileImgRepository.java
  back-end/src/main/java/com/studymate/backend/file/domain/ProfileImg.java
  back-end/src/main/java/com/studymate/backend/file/service/ProfileImgService.java
  back-end/src/main/java/com/studymate/backend/member/MemberMapper.java
  back-end/src/main/java/com/studymate/backend/member/MemberRepository.java
  back-end/src/main/java/com/studymate/backend/member/domain/Member.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberRequest.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberResponse.java
  back-end/src/main/java/com/studymate/backend/member/dto/MemberUpdateRequest.java
Labels: 기능구현

#73 [Feat] 질문 작성 api 구현
  back-end/src/main/java/com/studymate/backend/question/QuestionRepository.java
  back-end/src/main/java/com/studymate/backend/question/controller/QuestionController.java
  back-end/src/main/java/com/studymate/backend/question/domain/Question.java
  back-end/src/main/java/com/studymate/backend/question/dto/QuestionCreateRequest.java
  back-end/src/main/java/com/studymate/backend/question/dto/QuestionResponse.java
  back-end/src/main/java/com/studymate/backend/question/service/QuestionService.java
Labels: 기능구현

#75 feat: 멘토 10명 초기데이터 삽입(프로그레밍8, 영어2)
  back-end/src/main/resources/data.sql
Labels: 기능구현

#77 [Feat] 매칭 api 구현
  back-end/src/main/java/com/studymate/backend/matching/MatchingRepository.java
  back-end/src/main/java/com/studymate/backend/matching/controller/MatchingController.java
  back-end/src/main/java/com/studymate/backend/matching/domain/Matching.java
  back-end/src/main/java/com/studymate/backend/matching/dto/MatchingResponse.java
  back-end/src/main/java/com/studymate/backend/matching/service/MatchingService.java
  back-end/src/main/java/com/studymate/backend/member/service/MemberService.java
  back-end/src/main/resources/data.sql
Labels: 기능구현

#80 [fix]
  back-end/src/main/java/com/studymate/backend/comment/dto/response/CommentResponse.java
  back-end/src/main/java/com/studymate/backend/post/PostMapper.java
  back-end/src/main/java/com/studymate/backend/post/controller/PostController.java
  back-end/src/main/java/com/studymate/backend/post/dto/PostResponseDto.java
Labels: 오류수정

#82 [fix] 단건 조회 오류 해결
  back-end/src/main/java/com/studymate/backend/post/controller/PostController.java
  back-end/src/main/java/com/studymate/backend/post/service/PostService.java
Labels: 오류수정
